apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  USER: root
  #DATABASE_URL: mysql://mysql:3306/SpringWebYoutube?useTimezone=true&serverTimezone=UTC
  DATABASE_URL: mysql://10.50.10.69:3306/SpringWebYoutube?useTimezone=true&serverTimezone=UTC # caso esteja vinculando um clusterIP na mão
        