apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  template:
    metadata:
      name: pod-javadb
      labels:
        app: pod-javadb
    spec:
      containers:
        - name: container-pod-javadb
          image: projetofinal/spring-web-youtube
          ports:
            - containerPort: 3000

          resources:
            requests:
              memory: "800Mi" # 512 MB
              cpu: "1" # 0.5 milicors VCPU # este recurso tira do meu cluster este recurso #https://sysdig.com/blog/kubernetes-limits-requests/
            limits: # caso a aplicação precise de mais recurso, ele coloca este limite automático
              memory: "900Mi" # 800 MB
              cpu: "2"

  replicas: 2
  selector:
    matchLabels:
      app: pod-javadb
